local_costmap:
  global_frame:               odom
  rolling_window:             true
  track_unknown_space:        false
  width:                      12.0
  height:                     12.0
  origin_x:                   -6.0
  origin_y:                   -6.0
  
  
  plugins:
    - {name: obstacles_costmap2d,       type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,                 type: "costmap_2d::InflationLayer"}
