global_costmap:
  global_frame:              map
  rolling_window:            false
  track_unknown_space:       true

  plugins:
    - {name: gps_boundaries,       type: "segway_costmap_plugins::PolygonObstacleLayer"}
    - {name: obstacles_costmap2d,  type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,            type: "costmap_2d::InflationLayer"}




